# Generated by Django 5.0.9 on 2025-01-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_class', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseclassevent',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer'),
        ),
        migrations.AddField(
            model_name='exerciseclassoccurrence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='exercise_class.exerciseclassevent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_class.exerciseclassoccurrence'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('occurrence', 'participant')},
        ),
    ]
