# Generated by Django 5.0.9 on 2024-11-11 08:39

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseclassevent',
            name='schedule',
            field=recurrence.fields.RecurrenceField(),
        ),
    ]
