# Generated by Django 5.0.9 on 2024-11-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseclassoccurrence',
            options={},
        ),
        migrations.RemoveField(
            model_name='exerciseclassoccurrence',
            name='end',
        ),
        migrations.RemoveField(
            model_name='exerciseclassoccurrence',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='exerciseclassoccurrence',
            name='repeat_until',
        ),
        migrations.RemoveField(
            model_name='exerciseclassoccurrence',
            name='start',
        ),
    ]
