# Generated by Django 5.0.9 on 2024-11-04 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0002_alter_exerciseclassoccurrence_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseclassoccurrence',
            name='duration',
        ),
        migrations.AddField(
            model_name='exerciseclassevent',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseclassevent',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
