# Generated by Django 5.0.7 on 2024-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseclass',
            name='description',
            field=models.TextField(default='This is a class description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseclass',
            name='location',
            field=models.CharField(default='Room 1', max_length=50),
            preserve_default=False,
        ),
    ]
