# Generated by Django 5.0.7 on 2024-08-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseclass',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
