# Generated by Django 5.0.9 on 2024-11-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0003_remove_exerciseclassoccurrence_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseclassevent',
            old_name='recurrence',
            new_name='schedule',
        ),
    ]
