# Generated by Django 5.0.7 on 2024-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0003_exerciseclass_description_exerciseclass_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseclass',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
