# Generated by Django 5.0.9 on 2024-11-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0004_rename_recurrence_exerciseclassevent_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseclassoccurrence',
            name='participants',
        ),
    ]
