# Generated by Django 5.0.9 on 2024-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0005_remove_exerciseclassoccurrence_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseclassoccurrence',
            name='scheduled_date',
            field=models.DateField(),
        ),
    ]
