# Generated by Django 5.0.9 on 2024-11-06 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0006_alter_exerciseclassoccurrence_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseclassevent',
            name='end_time',
        ),
        migrations.AddField(
            model_name='exerciseclassevent',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
            preserve_default=False,
        ),
    ]
