# Generated by Django 5.0.9 on 2024-11-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_class', '0007_remove_exerciseclassevent_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseclassevent',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='exerciseclassoccurrence',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
