"""
Django settings for members_app project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-m17pw#6&!z1-+fxadty@6%50(m0aypj8+p)h&(b6bxl(7668q9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://*.gymlink.local",
    "https://django-members-app.communitygrounds.co.nz",
]

# Application definition

SHARED_APPS = [
    "django_tenants", # mandatory
    "tenant_manager", # you must list the app where your tenant model resides in

    "django.contrib.contenttypes",

    "unfold",
    "unfold.contrib.forms",  # optional, if special form elements are needed
    #"unfold.contrib.filters",  # optional, if special filters are needed
    # "unfold.contrib.inlines",  # optional, if special inlines are needed
    # "unfold.contrib.import_export",  # optional, if django-import-export package is used
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used


    # everything below here is optional
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    "django.contrib.humanize",

    "users.apps.UsersConfig",

    "django_hv",
    "imagekit",
    "recurrence",
]

TENANT_COLOR_ADMIN_APPS = False

TENANT_APPS = [

    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    "django.contrib.humanize",

    "django.contrib.contenttypes",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework.authtoken",

    "authentication.apps.AuthenticationConfig",
    "users.apps.UsersConfig",
    "workouts.apps.WorkoutsConfig",
    "trainers.apps.TrainersConfig",
    "exercise_class.apps.ExerciseClassConfig",
    "branding.apps.BrandingConfig",
    "notifications",
    "feed.apps.FeedConfig",  # This needs to be imported after the notifications app
]    

 # Avoid duplication of shared apps
INSTALLED_APPS = SHARED_APPS + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "members_app.middleware.TimezoneMiddleware",
]

ROOT_URLCONF = "members_app.urls"
PUBLIC_SCHEMA_URLCONF = "members_app.urls_public"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "branding.context_processors.branding", # Handles branding model customizations
            ],
            "libraries": {
                "custom_tags": "members_app.templatetags.custom_tags",
            },
        },
    },
]

WSGI_APPLICATION = "members_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.environ.get("POSTGRES_NAME"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("DB_HOST", default="db"),
        "PORT": 5432,
    }
}

DATABASE_ROUTERS = (
    "django_tenants.routers.TenantSyncRouter",
)

TENANT_MODEL = "tenant_manager.Tenant"
TENANT_DOMAIN_MODEL = "tenant_manager.Domain"
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True
PUBLIC_SCHEMA_NAME = "public"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework_xml.parsers.XMLParser",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework_xml.renderers.XMLRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True

NOTIFICATIONS_NOTIFICATION_MODEL = "feed.Notification"

# Celery settings
CELERY_BROKER_URL = "redis://redis:6379"
CELERY_RESULT_BACKEND = "redis://redis:6379"

UNFOLD_TENANT = {
    "SIDEBAR": {
    "show_search": False,  # Search in applications and models names
    "show_all_applications": False,  # Dropdown with all applications and models
    "navigation": [
        {
            "title": _("Navigation"),
            "separator": True,  # Top border
            "collapsible": True,  # Collapsible group of links
            "items": [
                {
                    "title": _("Dashboard"),
                    "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                    "link": reverse_lazy("admin:index"),
                    "permission": lambda request: request.user.is_superuser,
                },
                {
                    "title": _("Tenants"),
                    "icon": "people",
                    "link": reverse_lazy("admin:tenant_manager_tenant_changelist"),
                },
                {
                    "title": _("Domains"),
                    "icon": "domain",
                    "link": reverse_lazy("admin:tenant_manager_domain_changelist"),
                },

            ],
        },
        ],
    },
}

UNFOLD = {
    "SIDEBAR": {
    "show_search": False,  # Search in applications and models names
    "show_all_applications": False,  # Dropdown with all applications and models
    "navigation": [
        {
            "title": _("Navigation"),
            "separator": True,  # Top border
            "collapsible": True,  # Collapsible group of links
            "items": [
                {
                    "title": _("Dashboard"),
                    "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                    "link": reverse_lazy("admin:index"),
                    "badge": "sample_app.badge_callback",
                    "permission": lambda request: request.user.is_superuser,
                },
                {
                    "title": _("Users"),
                    "icon": "people",
                    "link": reverse_lazy("admin:users_user_changelist"),
                },
                {
                    "title": _("Workouts"),
                    "icon": "fitness_center",
                    "link": reverse_lazy("admin:workouts_workout_changelist"),
                },
                {
                    "title": _("Trainers"),
                    "icon": "directions_run",
                    "link": reverse_lazy("admin:trainers_trainer_changelist"),
                },
                {
                    "title": _("Classes"),
                    "icon": "school",
                    "link": reverse_lazy("admin:exercise_class_exerciseclassevent_changelist"),
                },
                {
                    "title": _("Feed"),
                    "icon": "rss_feed",
                    "link": reverse_lazy("admin:feed_notification_changelist"),
                },
                {
                    "title": _("Branding"),
                    "icon": "palette",
                    "link": reverse_lazy("admin:branding_branding_changelist"),
                }
            ],
        },
        ],
    },
}