# Generated by Django 5.0.7 on 2024-09-30 08:05
from django.db import migrations


def populate_exercises(apps, schema_editor):
    # Get the Exercise model
    Exercise = apps.get_model("workouts", "Exercise")

    # Define the exercises to populate
    exercises = [
        {
            "name": "Squat",
            "description": "Lower-body exercise that targets the legs and glutes. Form: Keep chest up, back straight, and knees over toes.",
        },
        {
            "name": "Deadlift",
            "description": "Full-body lift focusing on hamstrings, glutes, and back. Form: Keep back flat, lift with legs, and drive through heels.",
        },
        {
            "name": "Bench Press",
            "description": "Chest exercise that works shoulders and triceps. Form: Lower the bar to the chest, press upward with controlled movement.",
        },
        {
            "name": "Overhead Press",
            "description": "Shoulder exercise targeting upper body. Form: Press the weight overhead, avoid arching your lower back.",
        },
        {
            "name": "Barbell Row",
            "description": "Back exercise targeting lats and traps. Form: Keep back flat, pull the barbell toward your torso.",
        },
        {
            "name": "Pull-Up",
            "description": "Bodyweight exercise for the back and biceps. Form: Pull yourself up until your chin clears the bar.",
        },
        {
            "name": "Romanian Deadlift",
            "description": "Hamstring-focused deadlift variation. Form: Hinge at the hips, keep the bar close to your legs, and lower with control.",
        },
        {
            "name": "Lunge",
            "description": "Leg exercise targeting quads and glutes. Form: Step forward, lower both knees, and keep your torso upright.",
        },
        {
            "name": "Bicep Curl",
            "description": "Bicep isolation exercise. Form: Curl the weight while keeping your elbows stationary.",
        },
        {
            "name": "Tricep Dip",
            "description": "Bodyweight exercise for triceps and chest. Form: Lower yourself by bending your elbows, press back up.",
        },
    ]

    # Create or update exercises
    for exercise in exercises:
        Exercise.objects.get_or_create(
            name=exercise["name"], defaults={"description": exercise["description"]}
        )


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_exercises),
    ]
