# Generated by Django 5.0.7 on 2024-10-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_populate_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
