# Generated by Django 5.0.7 on 2024-10-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_difficulty_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='youtube_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
