# Generated by Django 5.0.9 on 2024-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercise_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
