# Generated by Django 5.0.9 on 2025-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_notification',
            field=models.BooleanField(default=False),
        ),
    ]
