service: members_app
image: tkhap/members_app

ssh:
  user: root

env:
  secret:
    - POSTGRES_NAME
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
  clear:
    DB_HOST: members_app-db
    REDIS_HOST: members_app-redis
    DJANGO_DEBUG: False
    S3_BUCKET_NAME: members-app-media
    S3_ENDPOINT_URL: https://01691522d1b29d249548ed4899775e34.r2.cloudflarestorage.com

proxy:
  ssl: true
  hosts:
   - gymlink.cloud
   - demogym.gymlink.cloud
  app_port: 8000 
  healthcheck:
    path: /health

servers:
  web:
    hosts:
      - 209.38.31.70 

  worker:
    hosts:
      - 209.38.31.70

  scheduler:
    hosts:
      - 209.38.31.70

accessories:
  db:
    image: postgres:17
    host: 209.38.31.70  
    port: 127.0.0.1:5432:5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    host: 209.38.31.70
    port: 127.0.0.1:6379:6379
    cmd: --maxmemory 200m --maxmemory-policy allkeys-lru
    volumes:
      - /var/redis/data:/data