# Generated by Django 5.0.9 on 2025-01-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='branding/logos/')),
                ('primary_color', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
