# Generated by Django 5.0.9 on 2025-01-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='primary_color',
            field=models.CharField(blank=True, default='#6750A4', max_length=255, null=True),
        ),
    ]
