# Generated by Django 5.0.9 on 2025-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_alter_branding_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='secondary_color',
            field=models.CharField(blank=True, default='#E8DEF8', max_length=255, null=True),
        ),
    ]
